project_id = "pomvobmwzlaihyrkrlia"

[functions.kodbank-register]
verify_jwt = false

[functions.kodbank-login]
verify_jwt = false

[functions.kodbank-balance]
verify_jwt = false

[functions.kodbank-chat]
verify_jwt = false

[functions.kodbank-deposit]
verify_jwt = false

[functions.kodbank-transfer]
verify_jwt = false

[functions.kodbank-transactions]
verify_jwt = false
